# NumPy Arrays

In [20]:
import numpy as np

## Creating a NumPy Array

### 1-dimensional array

In [21]:
arr = np.array([1,2,3])

In [22]:
arr

array([1, 2, 3])

### 2-dimensional array

In [23]:
my_mat = [[1,2,3], [4,5,6], [7,8,9]]

In [24]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Indexing and slicing 

### Indexing 1-dimensional array

In [25]:
arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [26]:
arr[5]

5

### Slicing 1-dimensional array

In [27]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [28]:
arr[1:5]

array([1, 2, 3, 4])

In [13]:
arr[4:]

array([ 4,  5,  6,  7,  8,  9, 10])

In [14]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [16]:
slice_of_arr = arr[0:6]
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [18]:
slice_of_arr[:] = 15
slice_of_arr

array([15, 15, 15, 15, 15, 15])

### Indexing 2-dimensional array

In [59]:
arr_2d = np.array([[5,10,15], [20,25,30],[35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [61]:
arr_2d[0]

array([ 5, 10, 15])

In [67]:
arr_2d[0][0]

5

In [68]:
arr_2d[0,0]

5

### Slicing 2-dimensional array

In [64]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [65]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

### Conditional selection

In [73]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [76]:
bool_arr = arr > 4

In [77]:
# This will only return values where the condition is true
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [79]:
arr[arr>7]

array([ 8,  9, 10])

## NumPy Operations

### Broadcasting

In [ ]:
arr

In [29]:
arr[0:5] = 100

In [30]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [32]:
arr[0:4] *3

array([300, 300, 300, 300])

### Reshaping an array

In [43]:
ranarray = np.random.randint(0,50, 9)

In [44]:
ranarray

array([49, 43, 38, 34, 28, 32,  8, 35, 34])

In [45]:
ranarray.shape

(9,)

In [50]:
ranarray = ranarray.reshape(3,3)
ranarray

array([[49, 43, 38],
       [34, 28, 32],
       [ 8, 35, 34]])

In [51]:
ranarray.shape

(3, 3)

### Aggregate functions

In [36]:
ranarray

array([ 7,  3, 16, 23, 46, 47,  5, 15,  6])

In [37]:
ranarray.max()

47

In [38]:
ranarray.min()

3

In [39]:
ranarray.argmax()

5

In [40]:
ranarray.argmin()

1

### Copying

In [52]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [54]:
arr_copy = arr[4:7].copy()
arr_copy

array([100,   5,   6])

In [55]:
arr_copy[:] = 55

In [56]:
arr_copy

array([55, 55, 55])

In [57]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

### Arithmetic

In [80]:
arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [81]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [82]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [83]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [84]:
arr / arr

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

### Arthmetic with scalar functions

In [85]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [86]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [87]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

## Universal array functions

In [71]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [72]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [73]:
np.max(arr)

10

In [74]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [75]:
np.log(arr)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])