# Exercises

Answer all questions below or complete the given instructions

##### Import numpy as np

In [1]:
import numpy as np

##### Given the list below create an array named arr

In [2]:
lst = [1,2,3,4,5,6,7,8,9,10]

In [4]:
arr = np.array(lst)

##### Using the array created above, select out the number 5

In [5]:
arr[4]

5

##### Using the array created above, select out numbers 7-9

In [6]:
arr[6:9]

array([7, 8, 9])

##### Given the lst below create a matrix named mat

In [7]:
mat_lst = [[100,200,300], [400,500,600], [700,800,900]]

In [9]:
mat = np.array(mat_lst)
mat

array([[100, 200, 300],
       [400, 500, 600],
       [700, 800, 900]])

##### Using the matrx created above select out numbers 200 and 300

In [12]:
mat[0, 1:3]

array([200, 300])

##### Using the matrix created above select out number 500

In [13]:
mat[1,1]

500

##### Using the matrix created above select out numbers 600 and 900

In [19]:
mat[1:3,2]

array([600, 900])

##### Using the matrix created above select out all numbers greater than 500

In [20]:
mat[mat > 500]

array([600, 700, 800, 900])

##### Given the matrix created above return the minimum value

In [21]:
np.min(mat)

100